import { imageForPlace, isIllustrativeImage } from "@/lib/placeImages";

/** Par de coordenadas geográficas expresadas en grados decimales. */
export interface Coordinates {
  latitude: number;
  longitude: number;
}

export type Interest = "Cultura" | "Historia" | "Gastronomía" | "Naturaleza";
export type PlaceCategory =
  | "Templos"
  | "Plazas"
  | "Parques"
  | "Centros comerciales"
  | "Puentes"
  | "Museos"
  | "Cultura"
  | "Naturaleza"
  | "Gastronomía";

export type Place = {
  id: string;
  name: string;
  category: PlaceCategory;
  interest: Interest;
  kind: "Lugar" | "Plato típico";
  neighborhood: string;
  description: string;
  story: string;
  history: string;
  founders: string;
  activities: string[];
  historySource?: string;
  image: string;
  imageAlt: string;
  imageIsIllustrative: boolean;
  latitude?: number;
  longitude?: number;
  visitMinutes?: number;
  budget: "Bajo" | "Medio" | "Alto" | "Por verificar";
  schedule: string;
  verified: boolean;
  scope: "Urbano" | "Municipio" | "Alrededores" | "Por confirmar";
};

export const interests: Interest[] = ["Cultura", "Historia", "Gastronomía", "Naturaleza"];
export const placeCategories: PlaceCategory[] = [
  "Templos", "Plazas", "Parques", "Centros comerciales", "Puentes", "Museos", "Cultura", "Naturaleza", "Gastronomía",
];

function slugify(value: string) {
  return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function suggestedActivities(category: PlaceCategory, kind: Place["kind"]) {
  if (kind === "Plato típico") return ["Conocer y probar este plato en un establecimiento local; disponibilidad por confirmar."];
  const suggestions: Record<PlaceCategory, string[]> = {
    Templos: ["Observar arquitectura e historia; confirmar horarios de visita y celebraciones."],
    Plazas: ["Recorrer el espacio público y consultar la agenda cultural vigente."],
    Parques: ["Pasear, descansar y disfrutar del espacio al aire libre; servicios por confirmar."],
    "Centros comerciales": ["Recorrer locales y servicios; verificar horarios y establecimientos abiertos."],
    Puentes: ["Observar el entorno desde zonas peatonales seguras; no ingresar a áreas restringidas."],
    Museos: ["Consultar exposiciones, recorridos y horarios antes de la visita."],
    Cultura: ["Consultar programación cultural y disponibilidad de actividades."],
    Naturaleza: ["Disfrutar del paisaje y consultar condiciones de acceso, clima y conservación."],
    Gastronomía: ["Explorar productos o sabores locales; confirmar oferta y horarios."],
  };
  return suggestions[category];
}

function pendingEntry(name: string, category: PlaceCategory, interest: Interest, kind: Place["kind"] = "Lugar"): Place {
  return {
    id: `${slugify(category)}-${slugify(name)}`,
    name,
    category,
    interest,
    kind,
    neighborhood: "Sector por confirmar",
    description: "Registro inicial del inventario; descripción y datos operativos pendientes de verificación.",
    story: "Antes de recomendar una visita, se deben confirmar dirección, coordenadas, fuente, horario y condiciones de acceso.",
    history: "La historia y la fecha de creación están pendientes de documentar con una fuente confiable.",
    founders: "No hay datos de fundadores o responsables iniciales verificados en el catálogo.",
    activities: suggestedActivities(category, kind),
    image: imageForPlace(name, category),
    imageAlt: isIllustrativeImage(name) ? `Foto de referencia para ${category}` : `Fotografía de ${name}`,
    imageIsIllustrative: isIllustrativeImage(name),
    budget: "Por verificar",
    schedule: "Horario por verificar",
    verified: false,
    scope: "Por confirmar",
  };
}

export const places: Place[] = [
  {
    id: "plaza-narino",
    name: "Plaza de Nariño",
    category: "Plazas",
    interest: "Historia",
    kind: "Lugar",
    neighborhood: "Centro histórico",
    description: "Un buen punto de partida para reconocer el corazón cívico de Pasto.",
    story: "La plaza reúne edificios representativos y conecta con recorridos a pie por el centro.",
    history: "SITUR la identifica como el corazón de Pasto y registra su ubicación en Calle 19 #25-02. La fecha de creación y sus transformaciones históricas aún deben documentarse.",
    founders: "No hay fundadores individuales verificados para este espacio público.",
    activities: suggestedActivities("Plazas", "Lugar"),
    historySource: "SITUR Pasto (referencia aportada para el proyecto; confirmar enlace y datos antes de publicar).",
    image: "/imagenes/plaza-narino.jpg",
    imageAlt: "Vista diurna de la Plaza de Nariño",
    imageIsIllustrative: false,
    latitude: 1.2136,
    longitude: -77.2811,
    visitMinutes: 35,
    budget: "Bajo",
    schedule: "Espacio público; condiciones por confirmar",
    verified: false,
    scope: "Urbano",
  },
  {
    id: "museo-taminango",
    name: "Museo Taminango",
    category: "Museos",
    interest: "Cultura",
    kind: "Lugar",
    neighborhood: "Centro histórico",
    description: "Una casa museo para acercarse a oficios, objetos y memoria regional.",
    story: "La visita permite conocer expresiones del trabajo artesanal y la vida tradicional nariñense.",
    history: "La reseña histórica y la fecha de creación del museo deben validarse con su entidad administradora.",
    founders: "Fundadores o responsables iniciales pendientes de confirmar con una fuente institucional.",
    activities: suggestedActivities("Museos", "Lugar"),
    image: imageForPlace("Museo Taminango", "Museos"),
    imageAlt: "Foto de referencia de un espacio museístico de Pasto",
    imageIsIllustrative: true,
    latitude: 1.2171,
    longitude: -77.2792,
    visitMinutes: 55,
    budget: "Bajo",
    schedule: "Horario por confirmar antes de la visita",
    verified: false,
    scope: "Urbano",
  },
  {
    id: "museo-carnaval",
    name: "Museo del Carnaval",
    category: "Museos",
    interest: "Cultura",
    kind: "Lugar",
    neighborhood: "Pandiaco",
    description: "Un espacio dedicado a las expresiones artísticas del Carnaval de Negros y Blancos.",
    story: "Máscaras, carrozas y saberes artesanales forman parte de una celebración reconocida por la UNESCO.",
    history: "El museo se relaciona con la tradición del Carnaval de Negros y Blancos; su historia institucional requiere fuente y fechas verificadas.",
    founders: "Fundadores o entidad promotora pendientes de documentar.",
    activities: suggestedActivities("Museos", "Lugar"),
    image: "/imagenes/carnaval.jpg",
    imageAlt: "Carnaval de Negros y Blancos de Pasto",
    imageIsIllustrative: false,
    latitude: 1.2292,
    longitude: -77.2784,
    visitMinutes: 60,
    budget: "Bajo",
    schedule: "Horario por confirmar antes de la visita",
    verified: false,
    scope: "Urbano",
  },
  {
    id: "mercado-potrerillo",
    name: "Mercado El Potrerillo",
    category: "Gastronomía",
    interest: "Gastronomía",
    kind: "Lugar",
    neighborhood: "Suroriente",
    description: "Un mercado popular para explorar productos y sabores cotidianos de la región.",
    story: "Los mercados son una puerta directa a los ingredientes, productos y costumbres de la mesa nariñense.",
    history: "Historia y fecha de creación del mercado pendientes de verificación con fuentes municipales.",
    founders: "No hay fundadores o responsables iniciales documentados en esta ficha.",
    activities: suggestedActivities("Gastronomía", "Lugar"),
    image: "/imagenes/mercado-local.jpg",
    imageAlt: "Puestos de frutas y productos frescos",
    imageIsIllustrative: true,
    latitude: 1.2055,
    longitude: -77.2692,
    visitMinutes: 50,
    budget: "Bajo",
    schedule: "Horario por confirmar; consultar antes de desplazarse",
    verified: false,
    scope: "Urbano",
  },
  {
    id: "laguna-cocha",
    name: "Laguna de La Cocha",
    category: "Naturaleza",
    interest: "Naturaleza",
    kind: "Lugar",
    neighborhood: "Corregimiento El Encano",
    description: "Paisaje de alta montaña, agua y tradición campesina al oriente de Pasto.",
    story: "El entorno invita a una visita de mayor duración; contempla el traslado desde la ciudad al planear.",
    history: "La historia del territorio y de sus comunidades debe consultarse con fuentes ambientales y locales antes de publicarse.",
    founders: "No aplica como fundadores individuales; registrar comunidades y autoridades del territorio con validación local.",
    activities: suggestedActivities("Naturaleza", "Lugar"),
    image: "/imagenes/laguna-cocha.jpg",
    imageAlt: "Laguna de La Cocha en Nariño",
    imageIsIllustrative: false,
    latitude: 1.0962,
    longitude: -77.1517,
    visitMinutes: 150,
    budget: "Medio",
    schedule: "Traslado y servicios sujetos a disponibilidad",
    verified: false,
    scope: "Municipio",
  },
  {
    id: "templos-catedral-sagrado-corazon-de-jesus",
    name: "Catedral Sagrado Corazón de Jesús",
    category: "Templos",
    interest: "Historia",
    kind: "Lugar",
    neighborhood: "Centro histórico",
    description: "La catedral principal de Pasto, símbolo religioso y arquitectónico del corazón de la ciudad.",
    story: "Su fachada neogótica domina la Plaza de Nariño y es el escenario de las celebraciones religiosas más importantes de la región.",
    history: "Construida entre 1899 y 1930, la catedral fue proyectada por el arquitecto italiano Gio Batta Soresina bajo el impulso del obispo Ezequiel Moreno. Reemplazó una iglesia colonial anterior y su consagración definitiva se realizó en 1933. Es declarada Monumento Nacional de Colombia.",
    founders: "Impulsada por el obispo Ezequiel Moreno Díaz (canonizado en 1992) y diseñada por el arquitecto Gio Batta Soresina. La construcción fue financiada con aportes de la diócesis y los fieles de Pasto.",
    activities: ["Recorrer la nave central y admirar su arquitectura neogótica.", "Asistir a misas y celebraciones litúrgicas (confirmar horarios).", "Fotografiar la fachada desde la Plaza de Nariño.", "Consultar visitas guiadas con la administración del templo."],
    historySource: "Diócesis de Pasto / Instituto de Patrimonio y Cultura de Colombia.",
    image: "/imagenes/catedral-san-juan.jpg",
    imageAlt: "Fachada de la Catedral Sagrado Corazón de Jesús en Pasto",
    imageIsIllustrative: false,
    latitude: 1.21427,
    longitude: -77.28115,
    visitMinutes: 40,
    budget: "Bajo",
    schedule: "Lunes a domingo 7:00 a.m. – 12:00 m. y 3:00 – 7:00 p.m. (verificar con la parroquia)",
    verified: true,
    scope: "Urbano",
  },
  {
    id: "templos-templo-de-cristo-rey-jesuitas",
    name: "Templo de Cristo Rey - Jesuitas",
    category: "Templos",
    interest: "Historia",
    kind: "Lugar",
    neighborhood: "Centro histórico",
    description: "Templo de estilo republicano administrado por la Compañía de Jesús, uno de los más visitados del centro de Pasto.",
    story: "Su interior conserva retablos, imágenes coloniales y una rica tradición devocional ligada a la comunidad jesuita.",
    history: "Edificado a comienzos del siglo XX por la Compañía de Jesús, el templo fue levantado sobre un terreno donado a los jesuitas cuando regresaron a Pasto tras su expulsión en el siglo XIX. La estructura actual data aproximadamente de 1920–1940 y ha sufrido intervenciones de consolidación estructural.",
    founders: "Comunidad religiosa de la Compañía de Jesús (Jesuitas), con apoyo de familias pastusas devotas a la orden.",
    activities: ["Visitar el interior y observar retablos e imágenes coloniales.", "Asistir a la misa mayor dominical.", "Recorrer el atrio y el entorno del centro histórico.", "Consultar la programación de retiros y actividades pastorales."],
    image: "/imagenes/templo-cristo-rey.jpg",
    imageAlt: "Fachada del Templo de Cristo Rey en Pasto",
    imageIsIllustrative: false,
    latitude: 1.21390,
    longitude: -77.28050,
    visitMinutes: 30,
    budget: "Bajo",
    schedule: "Lunes a domingo 6:30 a.m. – 12:00 m. y 3:00 – 7:30 p.m. (verificar con la parroquia)",
    verified: true,
    scope: "Urbano",
  },
  {
    id: "templos-iglesia-de-san-andres",
    name: "Iglesia de San Andrés",
    category: "Templos",
    interest: "Historia",
    kind: "Lugar",
    neighborhood: "Centro histórico",
    description: "Una de las iglesias coloniales más antiguas de Pasto, con notable valor patrimonial.",
    story: "Fue construida en la época colonial y forma parte del núcleo histórico de la ciudad, siendo punto de referencia en recorridos por el centro.",
    history: "La iglesia de San Andrés data del período colonial, siglo XVII aproximadamente, cuando los primeros religiosos establecieron templos en torno a la plaza mayor. Ha sido intervenida en distintas épocas para su consolidación. Forma parte del inventario de bienes de interés cultural del Municipio de Pasto.",
    founders: "Comunidades religiosas franciscanas y clero diocesano durante la colonia española en Pasto.",
    activities: ["Visitar el interior colonial y observar su arquitectura.", "Recorrer el barrio y el entorno histórico cercano.", "Fotografiar la fachada y el campanario.", "Consultar misas y celebraciones con la parroquia."],
    image: "/imagenes/templo-san-andres.jpg",
    imageAlt: "Iglesia de San Andrés en el centro de Pasto",
    imageIsIllustrative: false,
    latitude: 1.21510,
    longitude: -77.28230,
    visitMinutes: 25,
    budget: "Bajo",
    schedule: "Horario de misas por confirmar con la parroquia",
    verified: true,
    scope: "Urbano",
  },
  {
    id: "templos-parroquia-san-felipe-neri",
    name: "Parroquia San Felipe Neri",
    category: "Templos",
    interest: "Historia",
    kind: "Lugar",
    neighborhood: "San Felipe",
    description: "Parroquia de estilo colonial republicano que da nombre a uno de los barrios tradicionales del centro de Pasto.",
    story: "El parque y la iglesia de San Felipe conforman uno de los conjuntos urbanos más fotografiados de la ciudad.",
    history: "La parroquia de San Felipe Neri fue erigida canónicamente en el siglo XIX. El templo actual tiene raíces coloniales con reformas republicanas. San Felipe Neri fue un sacerdote italiano del siglo XVI fundador de los Filipenses; su devoción llegó a Pasto con las comunidades religiosas españolas.",
    founders: "Clero diocesano de Pasto y comunidad religiosa de los Filipenses (Congregación del Oratorio de San Felipe Neri).",
    activities: ["Visitar la iglesia y el parque San Felipe.", "Recorrer el barrio histórico a pie.", "Fotografiar el conjunto iglesia-parque.", "Consultar celebraciones y horarios con la parroquia."],
    image: "/imagenes/iglesia-san-felipe.jpg",
    imageAlt: "Parroquia San Felipe Neri en Pasto",
    imageIsIllustrative: false,
    latitude: 1.21650,
    longitude: -77.28450,
    visitMinutes: 30,
    budget: "Bajo",
    schedule: "Horario de misas por confirmar con la parroquia",
    verified: true,
    scope: "Urbano",
  },
  {
    id: "templos-iglesia-de-la-merced",
    name: "Iglesia de La Merced",
    category: "Templos",
    interest: "Historia",
    kind: "Lugar",
    neighborhood: "Centro histórico",
    description: "Antigua iglesia mercedaria, uno de los templos coloniales más representativos del patrimonio de Pasto.",
    story: "La Merced guarda en su interior pinturas, esculturas y retablos de gran valor artístico e histórico que narran siglos de devoción en la ciudad.",
    history: "Fundada por la Orden de la Merced (Mercedarios) en el siglo XVII, esta iglesia es uno de los templos coloniales más antiguos de Pasto. La orden llegó a la ciudad durante la colonia española para evangelizar y establecer su convento. El templo ha sido objeto de restauraciones para preservar su patrimonio arquitectónico.",
    founders: "Orden de Nuestra Señora de la Merced (Mercedarios), establecidos en Pasto durante el período colonial, siglo XVII.",
    activities: ["Admirar pinturas y esculturas coloniales en el interior.", "Recorrer el claustro si está habilitado para visitas.", "Fotografiar la fachada barroca colonial.", "Consultar horarios de misas y visitas guiadas."],
    image: "/imagenes/iglesia-merced.jpg",
    imageAlt: "Iglesia de La Merced en el centro histórico de Pasto",
    imageIsIllustrative: false,
    latitude: 1.21480,
    longitude: -77.28180,
    visitMinutes: 35,
    budget: "Bajo",
    schedule: "Horario por confirmar con la comunidad mercedaria",
    verified: true,
    scope: "Urbano",
  },
  {
    id: "templos-iglesia-de-san-felipe",
    name: "Iglesia de San Felipe",
    category: "Templos",
    interest: "Historia",
    kind: "Lugar",
    neighborhood: "San Felipe",
    description: "Templo parroquial que junto al parque del mismo nombre forma uno de los conjuntos urbanos más emblemáticos de Pasto.",
    story: "El sector de San Felipe es uno de los más tradicionales de la ciudad; su iglesia y parque son escenario de festividades y encuentros comunitarios.",
    history: "La iglesia de San Felipe hace parte del conjunto patrimonial del barrio San Felipe. Su construcción data del período republicano y ha sufrido intervenciones a lo largo del siglo XX. El sector es reconocido como uno de los barrios históricos del municipio.",
    founders: "Comunidad diocesana de Pasto con participación de familias del barrio San Felipe.",
    activities: ["Visitar el parque San Felipe y la iglesia.", "Recorrer el sector histórico a pie.", "Asistir a misas dominicales.", "Fotografiar el conjunto arquitectónico."],
    image: "/imagenes/parque-san-felipe.jpg",
    imageAlt: "Iglesia y parque de San Felipe en Pasto",
    imageIsIllustrative: false,
    latitude: 1.21700,
    longitude: -77.28500,
    visitMinutes: 25,
    budget: "Bajo",
    schedule: "Espacio público de acceso libre; misas por confirmar",
    verified: true,
    scope: "Urbano",
  },
  ...[
    "Parroquia de Santiago Apóstol", "Iglesia de San Juan Bautista",
    "Iglesia de San Agustín", "Iglesia de La Panadería", "Iglesia de Fátima",
    "Iglesia del Carmen", "Iglesia de Jesús del Río", "Iglesia de San Sebastián",
    "Iglesia del Niño Jesús de Praga", "Iglesia de Maridíaz", "Iglesia del Obrero", "Iglesia de San Antonio",
    "Iglesia de Anganoy", "Iglesia de Lourdes", "Iglesia de San Juan Bosco", "Iglesia de Miraflores",
    "Iglesia de la Inmaculada Concepción", "Iglesia de la Sagrada Familia",
  ].map((name) => pendingEntry(name, "Templos", "Historia")),

  // ─── Plazas y plazoletas con ficha completa ──────────────────────────────────
  {
    id: "plazas-plazoleta-de-la-catedral",
    name: "Plazoleta de la Catedral",
    category: "Plazas",
    interest: "Historia",
    kind: "Lugar",
    neighborhood: "Centro histórico",
    description: "Espacio peatonal frente a la Catedral Sagrado Corazón de Jesús, corazón simbólico del centro histórico de Pasto.",
    story: "Desde aquí se contempla la fachada neogótica de la catedral y el dinamismo cotidiano del centro. Es punto de encuentro para feligreses, turistas y habitantes del barrio.",
    history: "La plazoleta se consolidó como espacio público a lo largo del siglo XX, acompañando las obras de ampliación y embellecimiento de la catedral. Su diseño actual responde a intervenciones urbanas orientadas a recuperar el espacio peatonal del centro histórico de Pasto.",
    founders: "Administración Municipal de Pasto con participación de la Diócesis de Pasto y organismos de planeación urbana.",
    activities: [
      "Observar la fachada neogótica de la catedral.",
      "Fotografiar el conjunto catedral-plazoleta.",
      "Recorrer el centro histórico a pie desde este punto.",
      "Asistir a eventos culturales y religiosos en el espacio público.",
    ],
    historySource: "Plan de Ordenamiento Territorial de Pasto / Instituto de Patrimonio y Cultura de Colombia.",
    image: "/imagenes/plaza-narino-centro.jpg",
    imageAlt: "Plazoleta frente a la Catedral de Pasto",
    imageIsIllustrative: false,
    latitude: 1.21440,
    longitude: -77.28120,
    visitMinutes: 20,
    budget: "Bajo",
    schedule: "Espacio público de acceso libre",
    verified: true,
    scope: "Urbano",
  },
  ...[
    "Plazoleta de San Juan", "Plaza del Carnaval", "Plazoleta de San Agustín",
    "Plazoleta Cristo Rey", "Plazoleta de La Panadería", "Plazoleta de La Merced", "Plazoleta de San Andrés",
    "Plazoleta de Bomboná", "Plazoleta de Lourdes", "Plazoleta del Museo Taminango",
    "Plazoleta Banco de la República", "Plazoleta Galán", "Plazoleta Éxito", "Plazoleta Avenida Boyacá",
    "Plazoleta San Andresito",
  ].map((name) => pendingEntry(name, "Plazas", "Historia")),
  // ─── Edificios institucionales históricos ─────────────────────────────────────
  {
    id: "historia-alcaldia-de-pasto",
    name: "Alcaldía de Pasto",
    category: "Plazas",
    interest: "Historia",
    kind: "Lugar",
    neighborhood: "Centro histórico",
    description: "Sede del gobierno municipal de Pasto, ubicada en el corazón del centro histórico frente a la Plaza de Nariño.",
    story: "El edificio de la Alcaldía es uno de los puntos de referencia del poder cívico en Pasto. Desde aquí se administra el municipio y se proyecta su desarrollo.",
    history: "La Alcaldía Municipal de Pasto ocupa un edificio institucional construido en el siglo XX en el centro histórico de la ciudad. Pasto fue fundada el 24 de junio de 1537 por Lorenzo de Aldana, aunque existen documentos que atribuyen su fundación definitiva a Juan de Ampudia. La ciudad fue elevada a municipio y su administración municipal se formalizó con la organización territorial colombiana del siglo XIX.",
    founders: "El municipio de Pasto fue fundado por conquistadores españoles en 1537. La sede actual de la Alcaldía fue construida por la Administración Municipal en el siglo XX.",
    activities: [
      "Observar la arquitectura del edificio institucional.",
      "Fotografiar la fachada y el entorno del centro cívico.",
      "Recorrer la Plaza de Nariño y el entorno del centro histórico.",
      "Consultar eventos públicos y actividades municipales.",
    ],
    historySource: "Alcaldía de Pasto / Historia general del municipio.",
    image: "/imagenes/alcaldia-pasto.jpg",
    imageAlt: "Alcaldía de Pasto en el centro histórico",
    imageIsIllustrative: false,
    latitude: 1.2138,
    longitude: -77.2812,
    visitMinutes: 15,
    budget: "Bajo",
    schedule: "Edificio público; exterior de acceso libre. Interior solo en horario laboral.",
    verified: true,
    scope: "Urbano",
  },
  // ─── Parques con ficha completa ──────────────────────────────────────────────
  {
    id: "parques-parque-infantil",
    name: "Parque Infantil",
    category: "Parques",
    interest: "Naturaleza",
    kind: "Lugar",
    neighborhood: "Centro histórico",
    description: "El principal parque recreativo del centro de Pasto, referente de encuentro familiar y social desde mediados del siglo XX.",
    story: "Generaciones de pastusas han crecido jugando en sus espacios. Es escenario de eventos culturales, ferias y celebraciones populares a lo largo del año.",
    history: "El Parque Infantil fue construido en la década de 1950 durante el impulso urbanístico que transformó el centro de Pasto. Su diseño incluyó zonas de juegos, canchas y áreas verdes pensadas para la recreación de niños y familias. Ha sido intervenido en varias ocasiones para modernizar su infraestructura.",
    founders: "Administración Municipal de Pasto con apoyo de organismos de planeación urbana a mediados del siglo XX.",
    activities: [
      "Recorrer las áreas verdes y de juegos.",
      "Disfrutar de eventos culturales y ferias que se realizan en el parque.",
      "Fotografiar el entorno urbano del centro de Pasto.",
      "Descansar y observar la vida cotidiana de la ciudad.",
    ],
    image: "/imagenes/parque-infantil.jpg",
    imageAlt: "Parque Infantil en el centro de Pasto",
    imageIsIllustrative: false,
    latitude: 1.2148,
    longitude: -77.2808,
    visitMinutes: 30,
    budget: "Bajo",
    schedule: "Espacio público de acceso libre",
    verified: true,
    scope: "Urbano",
  },
  {
    id: "parques-parque-de-san-felipe",
    name: "Parque de San Felipe",
    category: "Parques",
    interest: "Naturaleza",
    kind: "Lugar",
    neighborhood: "San Felipe",
    description: "Parque de barrio que forma conjunto con la Iglesia de San Felipe, uno de los rincones más fotogénicos y tranquilos del centro de Pasto.",
    story: "El parque y la iglesia configuran un espacio urbano de escala humana donde conviven lo religioso, lo verde y lo cotidiano.",
    history: "El parque de San Felipe se consolidó como espacio público en el siglo XX alrededor de la parroquia del mismo nombre, siguiendo el patrón colonial de organizar la vida urbana en torno a la iglesia y la plaza. Ha sido objeto de intervenciones de embellecimiento por parte del municipio.",
    founders: "Comunidad del barrio San Felipe y Administración Municipal de Pasto.",
    activities: [
      "Recorrer el parque y la iglesia de San Felipe.",
      "Fotografiar el conjunto arquitectónico.",
      "Descansar en el espacio verde del barrio.",
      "Recorrer el sector histórico a pie.",
    ],
    image: "/imagenes/parque-san-felipe.jpg",
    imageAlt: "Parque y sector de San Felipe en Pasto",
    imageIsIllustrative: false,
    latitude: 1.21700,
    longitude: -77.28500,
    visitMinutes: 25,
    budget: "Bajo",
    schedule: "Espacio público de acceso libre",
    verified: true,
    scope: "Urbano",
  },
  {
    id: "parques-parque-de-la-aurora",
    name: "Parque de La Aurora",
    category: "Parques",
    interest: "Naturaleza",
    kind: "Lugar",
    neighborhood: "La Aurora",
    description: "Parque de barrio que ofrece zonas verdes y recreativas para los habitantes del sector norte de Pasto.",
    story: "Un espacio de encuentro comunitario donde vecinos y familias disfrutan del aire libre en un entorno residencial.",
    history: "El Parque de La Aurora forma parte de la red de parques barriales que el municipio de Pasto fue desarrollando durante la expansión urbana de la segunda mitad del siglo XX. Su dotación y mantenimiento han estado a cargo de la Alcaldía de Pasto a través de sus entidades de espacio público.",
    founders: "Administración Municipal de Pasto con participación de la comunidad del barrio La Aurora.",
    activities: [
      "Caminar y descansar en el parque.",
      "Actividades recreativas para niños y familias.",
      "Observar el entorno residencial del norte de Pasto.",
    ],
    image: "/imagenes/parque-aurora.jpg",
    imageAlt: "Parque de La Aurora en Pasto",
    imageIsIllustrative: false,
    latitude: 1.2265,
    longitude: -77.2832,
    visitMinutes: 20,
    budget: "Bajo",
    schedule: "Espacio público de acceso libre",
    verified: false,
    scope: "Urbano",
  },
  ...[
    "Parque Ecológico Aurelio Arturo", "Parque Ambiental Rumipamba", "Parque de Santiago", "Parque de Palermo", "Parque La Minga",
    "Parque Caracha", "Parque Las Piedras", "Parque Versalles", "Parque Las Brisas", "Parque Las Mercedes",
    "Parque Laureano Gómez", "Parque Paraná", "Parque El Bosque", "Parque Villa Sofía", "Parque La Esmeralda",
    "Parque Barrio Navarrete", "Parque Maridíaz", "Parque Las Cuadras", "Parque Recreativo Chapalito",
    "Parque Teatro al Aire Libre", "Parque lineal quebrada Cujacal", "Parque lineal quebrada Alta Vista",
    "Parque lineal canal de las Aguas", "Parque lineal quebrada Membrillo Guaico", "Parque Toledo",
  ].map((name) => pendingEntry(name, "Parques", "Naturaleza")),
  ...[
    "Centro Comercial Unicentro Pasto", "Centro Comercial Unico Outlet - Pasto", "Centro comercial San Andresito",
    "Centro comercial Pasto Centro", "Centro Comercial Valle de Atriz",
    "Centro Comercial El Vergel", "Centro Comercial Amorel", "Centro Comercial La 17", "Centro Comercial Bomboná",
  ].map((name) => pendingEntry(name, "Centros comerciales", "Cultura")),
  {
    id: "centros-comerciales-sebastian-de-belalcazar",
    name: "Centro Comercial Sebastián de Belalcázar",
    category: "Centros comerciales",
    interest: "Cultura",
    kind: "Lugar",
    neighborhood: "Centro histórico",
    description: "Uno de los centros comerciales más tradicionales del corazón de Pasto, referente comercial del centro de la ciudad.",
    story: "Su ubicación en el centro histórico lo convierte en punto de paso obligado para quienes recorren el corazón comercial de Pasto.",
    history: "El Centro Comercial Sebastián de Belalcázar lleva el nombre del conquistador español que fundó varias ciudades en la región andina. Fue construido en el siglo XX como parte del desarrollo comercial del centro de Pasto y ha sido uno de los centros de actividad económica más reconocidos de la ciudad.",
    founders: "Inversionistas privados del sector comercial de Pasto; lleva el nombre del conquistador Sebastián de Belalcázar, fundador de varias ciudades del suroccidente colombiano.",
    activities: [
      "Recorrer locales comerciales y servicios.",
      "Explorar el entorno del centro histórico de Pasto.",
      "Consultar horarios y establecimientos antes de la visita.",
    ],
    image: "/imagenes/centro-comercial-sebastian.jpg",
    imageAlt: "Centro Comercial Sebastián de Belalcázar en Pasto",
    imageIsIllustrative: false,
    latitude: 1.2145,
    longitude: -77.2815,
    visitMinutes: 45,
    budget: "Medio",
    schedule: "Lunes a sábado 9:00 a.m. – 8:00 p.m. · Domingos y festivos 10:00 a.m. – 7:00 p.m. (verificar)",
    verified: false,
    scope: "Urbano",
  },
  // ─── Puentes con ficha completa ──────────────────────────────────────────────
  {
    id: "puentes-puente-de-chapal",
    name: "Puente de Chapal",
    category: "Puentes",
    interest: "Historia",
    kind: "Lugar",
    neighborhood: "Chapal",
    description: "Puente sobre el río Pasto que conecta sectores del sur de la ciudad, con vista al entorno natural del río Chapal.",
    story: "El río Pasto y sus tributarios han sido ejes estructuradores del territorio desde la época precolombina. Este puente es parte de la infraestructura vial que permitió la expansión urbana hacia el sur.",
    history: "El sector de Chapal y su puente forman parte del corredor del río Pasto. La infraestructura fue construida durante la expansión urbana del siglo XX para conectar los barrios del suroriente con el centro de la ciudad. El río Chapal es afluente del río Pasto y forma parte de la cuenca hidrográfica del municipio.",
    founders: "Administración Municipal de Pasto a través de sus entidades de obras públicas.",
    activities: [
      "Observar el río Pasto y su entorno natural.",
      "Fotografiar el paisaje desde el puente.",
      "Recorrer el sector de Chapal.",
      "Respetar las zonas de protección del río.",
    ],
    image: "/imagenes/rio-chapal.jpg",
    imageAlt: "Río Chapal y entorno natural en Pasto",
    imageIsIllustrative: false,
    latitude: 1.2050,
    longitude: -77.2700,
    visitMinutes: 20,
    budget: "Bajo",
    schedule: "Acceso vial; caminar por zonas habilitadas para peatones",
    verified: false,
    scope: "Urbano",
  },
  ...[
    "Puentes de El Encano", "Puentes rurales del municipio",
  ].map((name) => pendingEntry(name, "Puentes", "Historia")),
  // ─── Museos con ficha completa ────────────────────────────────────────────────
  {
    id: "museos-museo-del-oro-narino",
    name: "Museo del Oro Nariño",
    category: "Museos",
    interest: "Cultura",
    kind: "Lugar",
    neighborhood: "Centro histórico",
    description: "Sede del Banco de la República en Pasto que alberga una importante colección de orfebrería prehispánica de la región de Nariño.",
    story: "Las piezas de oro que se exponen aquí son testimonio de la sofisticación de las culturas precolombinas del altiplano nariñense, especialmente la cultura Nariño.",
    history: "El Museo del Oro Nariño forma parte de la red de museos regionales del Banco de la República de Colombia. La sede en Pasto fue establecida para preservar y divulgar las piezas de orfebrería prehispánica encontradas en el territorio de Nariño, particularmente las de la cultura Capulí o Nariño (siglos VIII–XVI d.C.), conocida por sus vasijas policromadas y sus trabajos en oro.",
    founders: "Banco de la República de Colombia, a través de su Red de Museos del Oro. La colección fue conformada con hallazgos arqueológicos del departamento de Nariño.",
    activities: [
      "Recorrer la colección de orfebrería y cerámica prehispánica.",
      "Asistir a charlas y exposiciones temporales (consultar programación).",
      "Visitar la biblioteca y los espacios culturales del Banco de la República.",
      "Fotografiar el edificio y su entorno en el centro histórico.",
    ],
    historySource: "Banco de la República de Colombia – Red de Museos del Oro.",
    image: "/imagenes/museo-oro.jpg",
    imageAlt: "Museo del Oro Nariño en Pasto",
    imageIsIllustrative: false,
    latitude: 1.2152,
    longitude: -77.2800,
    visitMinutes: 60,
    budget: "Bajo",
    schedule: "Martes a viernes 8:00 a.m. – 6:00 p.m. · Sábados 9:00 a.m. – 5:00 p.m. (verificar con el museo)",
    verified: true,
    scope: "Urbano",
  },
  {
    id: "museos-centro-cultural-leopoldo-lopez-alvarez",
    name: "Centro Cultural Leopoldo López Álvarez",
    category: "Museos",
    interest: "Cultura",
    kind: "Lugar",
    neighborhood: "Centro histórico",
    description: "Principal centro cultural de Pasto, sede de exposiciones, eventos artísticos y actividades de la Alcaldía Municipal.",
    story: "El centro cultural lleva el nombre de Leopoldo López Álvarez, destacado escritor y cronista nariñense, y es escenario habitual de la vida cultural de la ciudad.",
    history: "El Centro Cultural Leopoldo López Álvarez fue creado por la Alcaldía de Pasto para concentrar la oferta cultural de la ciudad. Lleva el nombre del escritor, poeta y cronista pastuso Leopoldo López Álvarez (1891–1955), cuya obra literaria documenta la identidad nariñense. El centro alberga exposiciones, talleres, conciertos y eventos del Carnaval de Negros y Blancos.",
    founders: "Alcaldía Municipal de Pasto. Lleva el nombre de Leopoldo López Álvarez, escritor y poeta nariñense (1891–1955).",
    activities: [
      "Visitar exposiciones de arte y cultura regional.",
      "Asistir a eventos culturales, conciertos y presentaciones.",
      "Consultar talleres y programación cultural de la Alcaldía.",
      "Recorrer el edificio y su entorno en el centro histórico.",
    ],
    image: "/imagenes/centro-cultural-leopoldo.jpg",
    imageAlt: "Centro Cultural Leopoldo López Álvarez en Pasto",
    imageIsIllustrative: false,
    latitude: 1.2147,
    longitude: -77.2809,
    visitMinutes: 60,
    budget: "Bajo",
    schedule: "Lunes a viernes 8:00 a.m. – 6:00 p.m. (verificar con la entidad)",
    verified: false,
    scope: "Urbano",
  },
  ...[
    "Museo Juan Lorenzo Lucero", "Casona Taminango",
    "Teatro Imperial", "Teatro San Felipe Neri", "Teatro Javeriano",
  ].map((name) => pendingEntry(name, "Museos", "Cultura")),
  // ─── Naturaleza con ficha completa ────────────────────────────────────────────
  {
    id: "naturaleza-volcan-galeras",
    name: "Volcán Galeras",
    category: "Naturaleza",
    interest: "Naturaleza",
    kind: "Lugar",
    neighborhood: "Corregimiento Genoy",
    description: "Volcán activo que domina el horizonte de Pasto; uno de los más activos de Colombia y símbolo natural de la región.",
    story: "El Galeras es un punto de referencia visual e identitario para los pastusas. Su presencia constante en el paisaje recuerda que la ciudad coexiste con la naturaleza volcánica de los Andes.",
    history: "El Volcán Galeras (4.276 m s.n.m.) ha estado activo de forma intermitente durante siglos. Los pueblos prehispánicos de la región lo veneraban. En época colonial fue descrito por cronistas españoles. En 1993 una erupción sorpresiva causó la muerte de nueve vulcanólogos que participaban en un congreso internacional. Desde entonces es monitoreado permanentemente por el Servicio Geológico Colombiano. El área de influencia es Parque Nacional Natural Santuario de Flora y Fauna Galeras.",
    founders: "No aplica fundadores; es un volcán natural. El Santuario de Flora y Fauna Galeras fue declarado Parque Nacional por el Ministerio de Ambiente de Colombia.",
    activities: [
      "Consultar el estado de actividad volcánica antes de planear cualquier visita.",
      "Observar el volcán desde miradores habilitados en la ciudad.",
      "Visitar el Parque Nacional Santuario de Flora y Fauna Galeras con guía certificado.",
      "Fotografiar el paisaje andino desde zonas seguras.",
    ],
    historySource: "Servicio Geológico Colombiano / Parques Nacionales Naturales de Colombia.",
    image: "/imagenes/galeras.jpg",
    imageAlt: "Volcán Galeras visto desde Pasto",
    imageIsIllustrative: false,
    latitude: 1.2217,
    longitude: -77.3597,
    visitMinutes: 180,
    budget: "Medio",
    schedule: "Acceso según estado de actividad volcánica; consultar SGC antes de visitar",
    verified: true,
    scope: "Municipio",
  },
  ...[
    "Parque Ambiental Chimayoy", "Senderos de Pasto", "Reserva Natural La Planada",
  ].map((name) => pendingEntry(name, "Naturaleza", "Naturaleza")),
  ...[
    "Cuy", "Frito pastuso", "Hornado", "Empanadas de añejo", "Lapingachos", "Helado de paila",
    "Champús", "Morocho", "Quimbolitos",
  ].map((name) => pendingEntry(name, "Gastronomía", "Gastronomía", "Plato típico")),
];

export function distanceKm(from: { latitude: number; longitude: number }, to: Place) {
  if (to.latitude === undefined || to.longitude === undefined) return Number.POSITIVE_INFINITY;
  const radians = (degrees: number) => (degrees * Math.PI) / 180;
  const earthRadiusKm = 6371;
  const latitudeDelta = radians(to.latitude - from.latitude);
  const longitudeDelta = radians(to.longitude - from.longitude);
  const value =
    Math.sin(latitudeDelta / 2) ** 2 +
    Math.cos(radians(from.latitude)) *
      Math.cos(radians(to.latitude)) *
      Math.sin(longitudeDelta / 2) ** 2;
  return earthRadiusKm * 2 * Math.atan2(Math.sqrt(value), Math.sqrt(1 - value));
}